from setuptools import setup, find_packages

setup(
    name='reactive-ai',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'aiohttp==3.10.8',
        'aioredis==2.0.1',
        'APScheduler==3.10.4',
        'async-timeout==4.0.3',
        'attrs==24.2.0',
        'beautifulsoup4==4.12.3',
        'certifi==2024.8.30',
        'cffi==1.16.0',
        'charset-normalizer==3.3.2',
        'click==8.1.7',
        'cryptography==41.0.4',
        'fastapi==0.104.0',
        'grpcio==1.66.2',
        'grpcio-tools==1.66.2',
        'httpx==0.27.2',
        'idna==3.4',
        'Jinja2==3.1.4',
        'joblib==1.4.2',
        'kafka-python==2.0.2',
        'six==1.16.0',
        'matplotlib==3.8.1',
        'numpy==1.26.4',
        'openai==1.16.1',
        'openpyxl==3.1.5',
        'pandas==2.2.3',
        'plotly==5.18.0',
        'protobuf==5.28.2',
        'pydantic==2.9.2',
        'python-dateutil==2.9.0.post0',
        'python-dotenv==1.0.0',
        'qdrant-client==1.11.3',
        'redis==5.0.1',
        'requests==2.32.3',
        'six==1.16.0',
        'starlette==0.27.0',
        'tenacity==8.2.1',
        'tqdm==4.66.5',
        'twilio==9.3.3',
        'typing_extensions==4.8.0',
        'urllib3==2.2.3',
        'uvicorn==0.23.2',
        'Werkzeug==3.0.4',
        'wikipedia==1.4.0',
        'setuptools',
        'build==1.2.2',
        'PyPDF2==3.0.1',
        'PyMuPDF==1.24.11',
        'tiktoken==0.8.0'
    ],
    entry_points={
        'console_scripts': [
            # Add command line scripts here
        ],
    },
    author='Kunal Tanti',
    author_email='kunal.tanti@outlook.com',
    description='A description of your project',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/yourusername/reactive-ai',
    include_package_data=True,
    package_data={
        '': ['../config.py'],
    },
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.6',
)
